name: flutter_easy_barcode
description: "Barcode scanner and creator application"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.18.1
  cupertino_icons: 1.0.2
  pretty_qr_code: 3.3.0
  mobile_scanner: 4.0.1
  flutter_native_splash: 2.3.11
  flutter_staggered_animations: 1.1.1
  flutter_svg: 2.0.10+1
  url_launcher: 6.2.5
  flutter_bloc: 8.1.4
  equatable: 2.0.5
  injectable: 2.3.2
  get_it: 7.6.7
  fluttertoast: 8.2.4
  permission_handler: 11.3.1
  flex_color_picker: 3.4.1
  image_picker: 1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.1
  injectable_generator: 2.4.1
  build_runner: 2.4.8

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/svg/
    - assets/app_icon/
    - assets/splash/

  fonts:
    - family: Vazir
      fonts:
        - asset: assets/font/vazir/vazir_bold.ttf
          weight: 700
        - asset: assets/font/vazir/vazir_medium.ttf
          weight: 500
        - asset: assets/font/vazir/vazir_regular.ttf
          weight: 400
        - asset: assets/font/vazir/vazir_light.ttf
          weight: 300
        - asset: assets/font/vazir/vazir_thin.ttf
          weight: 100

    - family: VazirFarsi
      fonts:
        - asset: assets/font/vazir_farsi/vazir_bold.ttf
          weight: 700
        - asset: assets/font/vazir_farsi/vazir_medium.ttf
          weight: 500
        - asset: assets/font/vazir_farsi/vazir_regular.ttf
          weight: 400
        - asset: assets/font/vazir_farsi/vazir_light.ttf
          weight: 300
        - asset: assets/font/vazir_farsi/vazir_thin.ttf
          weight: 100

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash/splash.png
  android_12:
    color: "#ffffff"
    image: assets/splash/splash.png