name: flutter_easy_barcode
description: "Barcode scanner and creator application"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.18.1
  cupertino_icons: 1.0.2
  pretty_qr_code: 3.2.1
  mobile_scanner: 4.0.0
  flutter_native_splash: 2.3.11
  flutter_staggered_animations: 1.1.1
  flutter_svg: 2.0.10+1
  url_launcher: 6.2.5
  flutter_bloc: 8.1.4
  equatable: 2.0.5
  injectable: 2.3.2
  get_it: 7.6.7
  fluttertoast: 8.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.1
  injectable_generator: 2.4.1
  build_runner: 2.4.8

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/svg/create_barcode.svg
    - assets/svg/scan_barcode.svg

    - assets/app_icon/app_icon.png
    - assets/app_icon/app_icon.svg

  fonts:
    - family: sans
      fonts:
       - asset: assets/font/iran_sans.ttf